version: '2'
services:
    inesapi-app:
        image: inesapi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://inesapi-postgresql:5432/inesapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    inesapi-postgresql:
        extends:
            file: postgresql.yml
            service: inesapi-postgresql
